volumes:
  mysql:

networks:
  chatgpt-network:

x-common-environments: &common-environments
  TZ: Asia/Shanghai
  JWT_SECRET: ${JWT_SECRET}

x-mysql-environments: &mysql-environments
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

x-redis-environments: &redis-environments
  REDIS_PASSWORD: ${REDIS_PASSWORD}

services:
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - chatgpt-network
    environment:
      <<: [ *common-environments ]
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "13306:3306"

  redis:
    image: bitnami/redis:latest
    restart: always
    networks:
      - chatgpt-network
    environment:
      <<: [ *common-environments, *redis-environments ]
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    networks:
      - chatgpt-network
    environment:
      <<: [ *common-environments ]
    ports:
      - "9411:9411"

  configserver:
    build:
      dockerfile: Dockerfile
      context: ./configserver
      args:
        - GIT_VERSION=${GIT_VERSION:-unspecified}
    image: miracle/chatgpt-configserver:latest
    restart: always
    networks:
      - chatgpt-network
    environment:
      <<: [ *common-environments ]
      JAVA_OPTS: "-Xms128m -Xmx512m"
    command:
      - "--spring.cloud.config.server.git.uri=https://github.com/miracle-kang/chatagent"
      - "--spring.cloud.config.server.git.searchPath=.springconfig"

  identity:
    build:
      dockerfile: Dockerfile
      context: ./identity
      args:
        - GIT_VERSION=${GIT_VERSION:-unspecified}
    image: miracle/chatgpt-identity:latest
    restart: always
    depends_on:
      - mysql
      - configserver
    networks:
      - chatgpt-network
    environment:
      <<: [ *common-environments, *mysql-environments, *redis-environments ]
      MYSQL_URL: "mysql://mysql:3306"
      MYSQL_DATABASE: chatgpt-identity
      REDIS_ADDRESS: "redis://redis:6379"
      REDIS_DATABASE: 0
      JAVA_OPTS: "-Xms128m -Xmx512m"
    command:
      - "--auth.root.auto-init=true"
      - "--auth.root.phones=${ROOT_PHONES}"
      - "--auth.allow-mock=true"
      - "--snowflake.node-id=101"
      - "--third-party.dingtalk.token=${DINGTALK_TOKEN}"
      - "--third-party.dingtalk.secret=${DINGTALK_SECRET}"
      - "--spring.cloud.config.enabled=false"
      - "--spring.cloud.config.uri=http://configserver:8888"
      - "--remote.agent.url=http://agent:8080"
      - "--remote.subscription.url=http://subscription:8080"
      - "--zipkin.base-url=http://zipkin:9411"
      - "--logging.level.web=debug"
      - "--feign.logging.level=HEADERS"

  subscription:
    build:
      dockerfile: Dockerfile
      context: ./subscription
      args:
        - GIT_VERSION=${GIT_VERSION:-unspecified}
    image: miracle/chatgpt-subscription:latest
    restart: always
    depends_on:
      - mysql
      - configserver
      - identity
    networks:
      - chatgpt-network
    environment:
      <<: [ *common-environments, *mysql-environments, *redis-environments ]
      MYSQL_URL: "mysql://mysql:3306"
      MYSQL_DATABASE: chatgpt-subscription
      REDIS_ADDRESS: "redis://redis:6379"
      REDIS_DATABASE: 1
      JAVA_OPTS: "-Xms128m -Xmx512m"
    command:
      - "--snowflake.node-id=102"
      - "--spring.cloud.config.enabled=false"
      - "--spring.cloud.config.uri=http://configserver:8888"
      - "--remote.identity.url=http://identity:8080"
      - "--remote.agent.url=http://agent:8080"
      - "--zipkin.base-url=http://zipkin:9411"
      - "--logging.level.web=debug"
      - "--feign.logging.level=HEADERS"

  agent:
    build:
      dockerfile: Dockerfile
      context: ./agent
      args:
        - GIT_VERSION=${GIT_VERSION:-unspecified}
    image: miracle/chatgpt-agent:latest
    restart: always
    depends_on:
      - mysql
      - configserver
      - identity
    networks:
      - chatgpt-network
    environment:
      <<: [ *common-environments, *mysql-environments, *redis-environments ]
      MYSQL_URL: "mysql://mysql:3306"
      MYSQL_DATABASE: chatgpt-agent
      REDIS_ADDRESS: "redis://redis:6379"
      REDIS_DATABASE: 2
      JAVA_OPTS: "-Xms128m -Xmx512m"
    command:
      - "--snowflake.node-id=102"
      - "--third-party.openai.token=${OPENAI_TOKEN}"
      - "--third-party.openai.proxy=none"
      - "--spring.cloud.config.enabled=false"
      - "--spring.cloud.config.uri=http://configserver:8888"
      - "--remote.identity.url=http://identity:8080"
      - "--remote.subscription.url=http://subscription:8080"
      - "--zipkin.base-url=http://zipkin:9411"
      - "--logging.level.web=debug"
      - "--feign.logging.level=HEADERS"

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    image: miracle/nginx-gateway:alpine
    restart: always
    networks:
      - chatgpt-network
    ports:
      - "8080:8080"