server:
  port: 8080
  forward-headers-strategy: framework

spring:

  # Spring Data JPA
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    #      naming:
    #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  # Flyway
  flyway:
    enabled: false
    clean-disabled: true
    locations: classpath:sql
    baseline-on-migrate: true

  messages:
    basename: i18n/messages

# Spring Doc
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  show-actuator: true
  enable-native-support: true
  writer-with-order-by-keys: true
  group-configs:
    - group: actuator
      display-name: 'Actuator'
      paths-to-match:
        - /actuator/**

auth:
  jwt:
    issuer: miraclekang.com
    expires-hours: 48
    key: fa6Y!#2zYfdnzD#Z@USNFlQIgMROqR6aNnPeHy%Yw$9eCtOnjt

# Logging
logging:
  level:
    web: debug
    com.miraclekang: debug
    org.flywaydb: debug
    org.springframework.cloud.config: debug

snowflake:
  enable: true
  node-id: 100
