server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: chatgpt-identity
  main:
    allow-bean-definition-overriding: true

  # Spring Cloud Config
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
      allow-override: true

  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.chatgpt/identity
    username: root
    password: root

  # Spring Data JPA
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      # Not compliant for native-image, may be a hibernate bug
      # naming:
      #   implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  messages:
    basename: i18n/messages

  # Flyway
  flyway:
    enabled: false
    clean-disabled: true
    locations: classpath:sql
    baseline-on-migrate: true

  freemarker:
    suffix: .ftl

  # Security
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: github-client-id
            client-secret: github-client-secret
            redirect-uri: "{baseUrl}/api/open/oauth2/login/{registrationId}"
          google:
            client-id: google-client-id
            client-secret: google-client-secret
            redirect-uri: "{baseUrl}/api/open/oauth2/login/{registrationId}"

  # Mail Server
  mail:
    sender: "no-reply@miraclekang.com"
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: apipassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Spring Doc
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  show-actuator: true
  enable-native-support: true
  writer-with-order-by-keys: true
  group-configs:
    - group: actuator
      display-name: 'Actuator'
      paths-to-match:
        - /actuator/**

# Actuator
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
      cors:
        allowed-origin-patterns: '*'
        allow-credentials: true
        allowed-headers: '*'
        allowed-methods: '*'
        max-age: 3600
        allowed-origins:
          - '127.0.0.1'
  health:
    db:
      enabled: true

# Logging
logging:
  level:
    com.trddao: debug
    org.flywaydb: debug
    org.springframework.cloud.config: debug

third-party:
  dingtalk:
    token: none
    secret: none

snowflake:
  enable: true
  node-id: 100

auth:
  allow-mock: true
  mock-auth-code: 666666
  root:
    auto-init: true
    phones: RootPhones
  jwt:
    issuer: miraclekang
    expires-hours: 48
    key: fa6Y!#2zYfdnzD#Z@USNFlQIgMROqR6aNnPeHy%Yw$9eCtOnjt

# Redis
redis:
  enabled: false
  address: redis://localhost:6379
  database: 0
  password: 123456

file:
  storage: directory
  directory:
    storage-path: /tmp/chatgpt-subscription/files