server:
  port: 8080
  forward-headers-strategy: framework

spring:

  # Spring Data JPA
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      # Not compliant for native-image, may be a hibernate bug
      # naming:
      #   implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  messages:
    basename: i18n/messages

  # Flyway
  flyway:
    enabled: false
    clean-disabled: true
    locations: classpath:sql
    baseline-on-migrate: true

  freemarker:
    suffix: .ftl

# Spring Doc
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  show-actuator: true
  enable-native-support: true
  writer-with-order-by-keys: true
  group-configs:
    - group: actuator
      display-name: 'Actuator'
      paths-to-match:
        - /actuator/**

# Logging
logging:
  level:
    com.miraclekang: debug
    org.flywaydb: debug
    org.springframework.cloud.config: debug

third-party:
  dingtalk:
    token: none
    secret: none

snowflake:
  enable: true
  node-id: 100

auth:
  allow-mock: true
  mock-auth-code: 666666
  root:
    auto-init: true
    phones: RootPhones
  jwt:
    issuer: miraclekang.com
    expires-hours: 48
    key: fa6Y!#2zYfdnzD#Z@USNFlQIgMROqR6aNnPeHy%Yw$9eCtOnjt

file:
  storage: directory
  directory:
    storage-path: /tmp/chatgpt-subscription/files