spring:
  cloud:
    config:
      enabled: false
    refresh:
      enabled: false

  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chatgpt-identity
    username: root
    password: root

redis:
  enabled: false
