server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: chatgpt-assistant
  main:
    allow-bean-definition-overriding: true

  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chatgpt-assistant
    username: root
    password: root

  # Spring Cloud Config
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
      allow-override: true
    refresh:
      enabled: false

  # Flyway
  flyway:
    enabled: false
    clean-disabled: true
    locations: classpath:sql
    baseline-on-migrate: true

# Actuator
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
      cors:
        allowed-origin-patterns: '*'
        allow-credentials: true
        allowed-headers: '*'
        allowed-methods: '*'
        max-age: 3600
        allowed-origins:
          - '127.0.0.1'
  health:
    db:
      enabled: true

# Spring Doc
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  show-actuator: true
  enable-native-support: true
  writer-with-order-by-keys: true
  group-configs:
    - group: actuator
      display-name: 'Actuator'
      paths-to-match:
        - /actuator/**

third-party:
  openai:
    token: none
    proxy: 127.0.0.1:1087
    system-message: You are a friendly and helpful teaching assistant.

auth:
  jwt:
    issuer: miraclekang.com
    expires-hours: 48
    key: fa6Y!#2zYfdnzD#Z@USNFlQIgMROqR6aNnPeHy%Yw$9eCtOnjt

snowflake:
  enable: true
  node-id: 100

# Redis
redis:
  enabled: false
  address: redis://localhost:6379
  database: 0
  password: 123456

# Logging
logging:
  level:
    com.trddao: debug
    org.flywaydb: debug
    org.springframework.cloud.config: debug
