server:
  port: 8080
  forward-headers-strategy: framework

spring:

  # Spring Data JPA
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  # Flyway
  flyway:
    enabled: false
    clean-disabled: true
    locations: classpath:sql
    baseline-on-migrate: true


# Spring Doc
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  show-actuator: true
  writer-with-order-by-keys: true
  group-configs:
    - group: actuator
      display-name: 'Actuator'
      paths-to-match:
        - /actuator/**

third-party:
  openai:
    token: none
    proxy: 127.0.0.1:1087
    system-message: You are a friendly and helpful teaching assistant.

auth:
  jwt:
    issuer: miraclekang.com
    expires-hours: 48
    key: fa6Y!#2zYfdnzD#Z@USNFlQIgMROqR6aNnPeHy%Yw$9eCtOnjt

snowflake:
  enable: true
  node-id: 100

# Logging
logging:
  level:
    com.miraclekang: debug
    org.flywaydb: debug
    org.springframework.cloud.config: debug
