{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- /*Config-server */}}
{{- $configServerFullName := include "helm.configserver.name" . -}}
{{- $configServerSvcPort := .Values.configserver.service.port | default .Values.service.port -}}
{{- /*Identity */}}
{{- $identityFullName := include "helm.identity.name" . -}}
{{- $identitySvcPort := .Values.identity.service.port | default .Values.service.port -}}
{{- /*Subscription*/}}
{{- $subscriptionFullName := include "helm.subscription.name" . -}}
{{- $subscriptionSvcPort := .Values.subscription.service.port | default .Values.service.port -}}
{{- /*agent*/}}
{{- $assistantFullName := include "helm.agent.name" . -}}
{{- $assistantSvcPort := .Values.agent.service.port | default .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    nginx.ingress.kubernetes.io/use-regex: "true"
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- /*default rule*/}}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- /*Config server rule*/}}
          {{- if $.Values.configserver.ingress.enabled }}
          {{- range $.Values.configserver.ingress.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $configServerFullName }}
                port:
                  number: {{ $configServerSvcPort }}
              {{- else }}
              serviceName: {{ $configServerFullName }}
              servicePort: {{ $configServerSvcPort }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- /*identity rule*/}}
          {{- if $.Values.identity.ingress.enabled }}
          {{- range $.Values.identity.ingress.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $identityFullName }}
                port:
                  number: {{ $identitySvcPort }}
              {{- else }}
              serviceName: {{ $identityFullName }}
              servicePort: {{ $identitySvcPort }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- /*subscription rule*/}}
          {{- if $.Values.subscription.ingress.enabled }}
          {{- range $.Values.subscription.ingress.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $subscriptionFullName }}
                port:
                  number: {{ $subscriptionSvcPort }}
              {{- else }}
              serviceName: {{ $subscriptionFullName }}
              servicePort: {{ $subscriptionSvcPort }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- /*agent rule*/}}
          {{- if $.Values.agent.ingress.enabled }}
          {{- range $.Values.agent.ingress.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $assistantFullName }}
                port:
                  number: {{ $assistantSvcPort }}
              {{- else }}
              serviceName: {{ $assistantFullName }}
              servicePort: {{ $assistantSvcPort }}
              {{- end }}
          {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
