apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-secret
data:
  mysql-username: {{ .Values.mysql.username | b64enc }}
  mysql-password: {{ .Values.mysql.password | b64enc }}
  {{- with .Values.redis.password }}
  redis-password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.thirdParty.dingtalk.token }}
  dingtalk-token: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.thirdParty.dingtalk.secret }}
  dingtalk-secret: {{ . | b64enc }}
  {{- end }}
  {{- if .Values.thirdParty.openai.token }}
  openai-token: {{ .Values.thirdParty.openai.token | b64enc }}
  {{- end }}
  {{- if .Values.mailServer.username }}
  mailServer-username: {{ .Values.mailServer.username | b64enc }}
  mailServer-password: {{ .Values.mailServer.password | b64enc }}
  {{- end }}
  {{- with .Values.auth.jwtSecret }}
  jwt-secret: {{ . | b64enc }}
  {{- end }}
  {{- if .Values.configserver.git.username }}
  {{- with .Values.configserver.git }}
  configserver-git-username: {{ .username | b64enc }}
  configserver-git-password: {{ .password | b64enc }}
  {{- end}}
  {{- end }}
