{{/*Config server service account*/}}
{{- if and .Values.configserver.enabled (default .Values.serviceAccount.create .Values.configserver.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.configserver.serviceAccountName" . }}
  labels:
    {{- include "helm.configserver.labels" . | nindent 4 }}
  {{- if or .Values.configserver.serviceAccount.annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.configserver.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{/*Identity service account*/}}
{{- if and .Values.identity.enabled (default .Values.serviceAccount.create .Values.identity.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.identity.serviceAccountName" . }}
  labels:
    {{- include "helm.identity.labels" . | nindent 4 }}
  {{- if or .Values.identity.serviceAccount.annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.identity.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{/*Subscription service account*/}}
{{- if and .Values.subscription.enabled (default .Values.serviceAccount.create .Values.subscription.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.subscription.serviceAccountName" . }}
  labels:
    {{- include "helm.subscription.labels" . | nindent 4 }}
  {{- if or .Values.subscription.serviceAccount.annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.subscription.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{/*Agent service account*/}}
{{- if and .Values.agent.enabled (default .Values.serviceAccount.create .Values.agent.serviceAccount.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.agent.serviceAccountName" . }}
  labels:
    {{- include "helm.agent.labels" . | nindent 4 }}
  {{- if or .Values.agent.serviceAccount.annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.agent.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}